name: 'Testing'

on:
  workflow_dispatch:  # click the button on Github repo!

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: ls -la
      - run: cd / && ls -la
      - run: cd $GITHUB_WORKSPACE && ls -la
      - run: cd ~ && ls -la
      - run: cd ~/actions-runner/_work/brave-browser-custom-sync/brave-browser-custom-sync && ls -la
      - run: npm help
